### PR TITLE
Update kubernetes-client version in k8s containers

### PR DESCRIPTION
**Pull request by pdostal**

### CODE REVIEW

**Comment by grisu48** [comment]
LGTM but a comment on the wording: I think "Update kubernetes-client" is the better sentence. "Fix" suggests that there was something broken, so it should describe what the problem was that has been fixed, not the action that has been taken.

**Comment by pdostal** [comment]
Sorry, I did the same mistake yesterday and few hours ago I do it again. Updated.

**Review by ricardobranco777 — APPROVED** [review]
LGTM.  Did you try to build the image locally?

Eventually we have to update google-cloud-cli soon.

**Comment by pdostal** [comment]
One hour ago:
```
$ podman run -it --rm registry.suse.com/bci/python:3.11
3a45e6c54be4 zypper se kubernetes
Trying to pull registry.suse.com/bci/python@sha256:1f6c3795c271d8c81f1ae457011b629904c50735a149cd943adb3a45e6c54be4...
Getting image source signatures
Checking if image destination supports signatures
Copying blob 2a3e9863a634 done   |
Copying blob d07ceef63959 done   |
Copying config 74f3a21e8d done   |
Writing manifest to image destination
Storing signatures
Refreshing service 'container-suseconnect-zypp'.
Retrieving repository 'SLE_BCI' metadata ....................................................................................................[done]
Building repository 'SLE_BCI' cache .........................................................................................................[done]
Loading repository data...
Reading installed packages...

S | Name                                       | Summary                                                               | Type
--+--------------------------------------------+-----------------------------------------------------------------------+--------
  | kubernetes1.28-client                      | Kubernetes client tools                                               | package
  | kubernetes1.28-client-common               | Kubernetes client tools common files                                  | package
  | python3-azure-mgmt-hybridkubernetes        | Microsoft Azure HybridKubernetes Management Client Library for Python | package
  | python3-azure-mgmt-kubernetesconfiguration | Microsoft Azure Kubernetes Configuration Management Client Library    | package
  | python3-kubernetes                         | Kubernetes python client                                              | package
```

Now:
```
$ podman run -it --rm registry.suse.com/bci/python:3.11 zypper se kubernetes
Refreshing service 'container-suseconnect-zypp'.
Retrieving repository 'SLE_BCI' metadata ....................................................................................................[done]
Building repository 'SLE_BCI' cache .........................................................................................................[done]
Loading repository data...
Reading installed packages...

S | Name                                       | Summary                                                            | Type
--+--------------------------------------------+--------------------------------------------------------------------+--------
  | kubernetes1.18-client                      | Kubernetes client tools                                            | package
  | kubernetes1.18-client-common               | Kubernetes client tools common files                               | package
  | python3-azure-mgmt-kubernetesconfiguration | Microsoft Azure Kubernetes Configuration Management Client Library | package
  | terraform-provider-kubernetes              | Terraform Kubernetes provider                                      | package
```

**Comment by pdostal** [comment]
```
Successfully tagged localhost/suse/qac/pcw-k8s-cleaner:latest
a0d6f1aad26ab0325366ed153bf7f50be1c14d12ef6a785340faf41f698783e4
```

**Pull request merged**
