### PR TITLE
Fix typo in Dockerfile_k8s_dev

### PR DESCRIPTION
**Pull request by pdostal**

### CODE REVIEW

**Review by ricardobranco777 — APPROVED** [review]
LGTM

**Comment by asmorodskyi** [comment]
please don't merge PRs with failed tests , this should be hard rule

**Comment by asmorodskyi** [comment]
ok I created a rule for master branch which will disable such ability ....

**Comment by ricardobranco777** [comment]
> please don't merge PRs with failed tests , this should be hard rule

In this case it was failing because the Selenium test was failing (reason: updated Selenium package).

I should have merged my PR fixing it first and told Pavel to rebase this one.

**Comment by ricardobranco777** [comment]
> ok I created a rule for master branch which will disable such ability ....

What will happen in the case of codecov failing?

**Comment by asmorodskyi** [comment]
> > please don't merge PRs with failed tests , this should be hard rule
> 
> In this case it was failing because the Selenium test was failing (reason: updated Selenium package).
> 
> I should have merged my PR fixing it first and told Pavel to rebase this one.

yes I get that part that Pavel's PR does not introduce the problem , but from my POV it does not change anything . When tests are failing repo considered as "broken" and should be fixed before anything else will be merged into it

**Pull request merged**
